    <footer>
      <div class ="footer-bottom">  
          <p><a href="https://kenzienguyen22.atlassian.net/jira/software/projects/SCRUM/boards/1/backlog?atlOrigin=eyJpIjoiMDMxZDQwMjA1OGE5NDUwMjhmMDY3MjZmY2MyNzNlZTYiLCJwIjoiaiJ9"
            target="_blank" rel="noopener noreferrer">
            &copy; 2025 ePass Software. All rights reserved.</p>
          <a href="https://github.com/106223201/project2" 
          target="_blank" rel="noopener noreferrer"> Check us out on Github!</p>
      </div>
    </footer>
