    <nav id="nav-bar">
        <a href="index.php"><img class="logo" src ="images/logo.png" alt ="logo"></a></li>
          
        <!-- menu bars -->
          <input type="checkbox" id="nav-toggle">
            <label for="nav-toggle" class="nav-toggle-label">
                <span></span>
                <span></span>
                <span></span>
            </label>       
        <ul id="nav-menu">
            <li><a id="nav-link" href="index.php">Home</a></li>
            <li><a id="nav-link" href="about.php">About</a></li>
            <li><a id="nav-link" href="jobs.php">Careers</a></li>
            <li><a id="nav-link" href="mailto:info@epasssoftware.com.au">Contact</a></li>
            <li><a id="nav-link" href="apply.php">Apply</a></li>
            <li><a id="nav-link" href="login-register.php">Sign in</a></li>
        </ul>
    </nav>
